SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b, AUTHOR a , BOOK_SALES s
WHERE b.AUTHOR_ID = a.AUTHOR_ID AND b.BOOK_ID = s.BOOK_ID
       AND s.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
