SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES s
WHERE  b.AUTHOR_ID = a.AUTHOR_ID AND s.SALES_DATE LIKE '2022-01%' AND b.BOOK_ID = s.BOOK_ID
GROUP BY a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;