SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i, ITEM_TREE t
WHERE i.ITEM_ID = t.ITEM_ID
    AND i.ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID
                   FROM ITEM_TREE
                    WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;