SELECT c.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
        , CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        , CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
WHERE c.CAR_ID = h.CAR_ID 
    AND c.CAR_TYPE = p.CAR_TYPE
    AND c.CAR_TYPE IN ('세단', 'SUV')
    AND c.CAR_ID NOT IN 
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE > '2022-11-01')
AND DURATION_TYPE = '30일 이상'
    -- AND END_DATE < '2022-11-01'
    AND p.DURATION_TYPE = '30일 이상'
    AND (c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) >= 500000 AND (c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) < 2000000
GROUP BY c.CAR_ID
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC;
