SELECT DISTINCT h.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h, CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
WHERE c.CAR_ID = h.CAR_ID AND c.CAR_TYPE = p.CAR_TYPE
    AND (c.CAR_TYPE LIKE '세단' OR c.CAR_TYPE LIKE 'SUV')
    AND h.CAR_ID NOT IN (SELECT CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE (END_DATE >= 20221101))
    AND (p.DURATION_TYPE LIKE '30%' OR p.DURATION_TYPE LIKE '90%')
    AND (FLOOR(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) >= 500000 AND FLOOR(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30) < 2000000)
GROUP BY h.CAR_ID
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;