SELECT DISTINCT u.USER_ID , u.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD b, USED_GOODS_USER u
WHERE u.USER_ID IN (SELECT WRITER_ID AS A
FROM USED_GOODS_BOARD
GROUP BY A
HAVING COUNT(A) >= 3)
ORDER BY USER_ID DESC;