SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID
    AND LEFT(i.SEX_UPON_INTAKE, 4) LIKE 'Inta'
    AND LEFT(o.SEX_UPON_OUTCOME, 4) IN ('Neut', 'Spay')
ORDER BY ANIMAL_ID;