SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT(o.USER_ID)) AS USERS
FROM USER_INFO u, ONLINE_SALE o
WHERE GENDER IS NOT NULL AND u.USER_ID = o.USER_ID
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), GENDER
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), GENDER;
