SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, i.GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM USER_INFO i, ONLINE_SALE s
WHERE i.USER_ID = s.USER_ID
    AND GENDER IS NOT NULL
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE), i.GENDER
ORDER BY YEAR, MONTH, GENDER;