SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT o.ANIMAL_ID
                        FROM ANIMAL_INS i, ANIMAL_OUTS o
                        WHERE i.ANIMAL_ID = o.ANIMAL_ID)
ORDER BY ANIMAL_ID, NAME;