-- 총 회원의 수 구하기
-- month 기준 회원 수 구하기 // COUNT(i.USER_ID)

SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, COUNT(DISTINCT(i.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(i.USER_ID)) / (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO
WHERE JOINED LIKE '2021-%'), 1) AS PUCHASED_RATIO
FROM USER_INFO i, ONLINE_SALE s
WHERE i.USER_ID = s.USER_ID
    AND i.JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;