SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE p.PRODUCT_ID = o.PRODUCT_ID
    AND PRODUCE_DATE LIKE '2022-05%'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID