SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b, USED_GOODS_USER u
WHERE b.WRITER_ID = u.USER_ID AND b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;